In [1]:
import numpy as np

print(np.__version__) # 1.15.1

#用简洁的表达式替代for-in循环
#生成大规模数组的效率高，快一个数量级

#print(a.ndim) # 3
#print(a.shape) # (2, 3, 6)
#print(a.dtype) # float64

1.19.2


In [3]:
#一维数据
array_1x6 = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=np.float64)
print(array_1x6)

[1. 2. 3. 4. 5. 6.]


In [7]:
#二维数据
#array_2x6 = np.array([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], [1.1, 2.1, 3.1, 4.1, 5.1, 6.1]])
a = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
b = [1.1, 2.1, 3.1, 4.1, 5.1, 6.1]
array_2x6 = np.array([a,b])
print(array_2x6) 

[[1.  2.  3.  4.  5.  6. ]
 [1.1 2.1 3.1 4.1 5.1 6.1]]


In [10]:
#三维数据
#array_2x3x6 = np.array([[[1.0,2.0,3.0,4.0,5.0,6.0],[1.1,2.1,3.1,4.1,5.1,6.1],[1.2,2.2,3.2,4.2,5.2,6.2]],
#                        [[7.0,8.0,9.0,10.0,11.0,12.0],[7.1,8.1,9.1,10.1,11.1,12.1],[7.2,8.2,9.2,10.2,11.2,12.2]]])
a1 = [1.0,2.0,3.0,4.0,5.0,6.0]
a2 = [1.1,2.1,3.1,4.1,5.1,6.1]
a3 = [1.2,2.2,3.2,4.2,5.2,6.2]
a = [a1,a2,a3]
b1 = [7.0,8.0,9.0,10.0,11.0,12.0]
b2 = [7.1,8.1,9.1,10.1,11.1,12.1]
b3 = [7.2,8.2,9.2,10.2,11.2,12.2]
b = [b1,b2,b3]
array_2x3x6 = np.array([a,b])
print(array_2x3x6)

[[[ 1.   2.   3.   4.   5.   6. ]
  [ 1.1  2.1  3.1  4.1  5.1  6.1]
  [ 1.2  2.2  3.2  4.2  5.2  6.2]]

 [[ 7.   8.   9.  10.  11.  12. ]
  [ 7.1  8.1  9.1 10.1 11.1 12.1]
  [ 7.2  8.2  9.2 10.2 11.2 12.2]]]


In [11]:
# np.array匹配相加
array_4x3_a = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]]) 
array_4x3_b = np.array([[5,5,5],[5,5,5],[5,5,5],[5,5,5]])
print(array_4x3_a+array_4x3_b)

[[6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]


In [12]:
# np.array标量相加
array_4x3_a = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]]) 
print(array_4x3_a+5)

[[6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]


In [13]:
# np.array矢量相加 dim = 1
array_4x3 = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
array_1x3 = np.array([1,2,3])
print(array_4x3 + array_1x3)

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [14]:
# np.array矢量相加 dim = 2
array_4x3 = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
array_4x1 = np.array([[1],[1],[1],[1]])
print(array_4x3 + array_4x1)

[[2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


In [15]:
# 1阵
array_one = np.ones(shape=(2, 4))
print(array_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
#填充阵
array_full = np.full(shape=(2, 4), fill_value=10)
print(array_full)

[[10 10 10 10]
 [10 10 10 10]]


In [20]:
# 单位矩阵
array_eye = np.eye(4, M=6)
print(array_eye)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [21]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) 等差数列
# start指定开始值;stop指定终值;num指定元素个数;endpoint指定等差数列是否包含终值
array_linspace = np.linspace(start=0, stop=5, num=10, endpoint=False)
print(array_linspace)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [25]:
# 设置相同的seed 每次生成的随机数相同 便于调试

np.random.seed(1)
# randint(low, high=None, size=None, dtype='l') # 指定上下限范围的随机数组
array_randint = np.random.randint(2, 4, size=10)
print(array_randint)

[3 3 2 2 3 3 3 3 3 2]


In [31]:
# 二项分布 
# binomial(n, p, size=None), 符合二项分布的随机数组, X-b(n,p)
array_binomial = np.random.binomial(10, 0.5, size=100)
print(array_binomial)

[7 6 7 3 3 4 5 7 9 6 6 7 5 4 4 3 6 3 4 6 4 8 4 5 4 7 4 5 5 7 2 6 7 2 5 4 7
 5 6 5 6 4 1 5 4 5 7 5 4 4 7 7 7 7 4 3 4 4 4 5 5 6 4 6 4 5 4 3 4 6 5 5 4 5
 9 6 5 8 7 5 2 3 3 5 4 8 3 8 6 6 6 6 5 2 4 5 6 5 5 3]


In [32]:
#标准正态分布
array_randn = np.random.randn(3, 4)
print(array_randn)

[[-0.66048031 -1.14562293  1.62918731  0.1527367 ]
 [-1.05828522 -0.10194848  0.04771979 -1.97987568]
 [ 1.11861489  0.71985978  1.37751003  0.08479693]]


In [33]:
#均匀分布
array_rand = np.random.rand(3, 4)
print(array_rand)

[[0.01260377 0.67246984 0.68680823 0.44924675]
 [0.91478869 0.64436108 0.00523984 0.48442845]
 [0.85931781 0.83039957 0.6491542  0.67369842]]


In [34]:
#正态分布
array_normal = np.random.normal(loc=10.0, scale=1.0, size=(1,3,2))
print(array_normal)

[[[ 8.37752106 10.56385598]
  [11.89579139 10.66821393]
  [10.9434644   9.60872319]]]


In [35]:
#计算sign
array_4x3_234 = np.array([[1, 0, 1], [-2, 2, 2], [3, -3, 3], [4, 4, -4]])
array_sign = np.sign(array_4x3_234)
print(array_sign)

[[ 1  0  1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]]


In [36]:
#计算非空
array_4x3_235 = np.array([[1, 1, 1], [-2, np.nan, 2], [3, np.nan, 3], [4, 4, -4]])
array_isnan = np.isnan(array_4x3_235)
print(array_isnan)

[[False False False]
 [False  True False]
 [False  True False]
 [False False False]]


In [37]:
# np.where(cond,x,y)：满足条件（cond）输出x，不满足输出y
array_4x3_236 = np.array([[1, 1, 1], [-2, 8, 2], [3, 9, 3], [4, 4, -4]])
array_where = np.where(array_4x3_236 > 5, 5, 0)
print(array_where)

[[0 0 0]
 [0 5 0]
 [0 5 0]
 [0 0 0]]


In [38]:
#np.array --> matrix
matrix_a = np.mat('1 3 5; 2 4 6')
matrix_b = np.mat([[1, 3, 5], [2, 4, 6]])

In [42]:
# dot
A = np.mat([[1, 2], [3, 4]])
B = np.mat([[1, 2], [3, 4]])
np.dot(A, B)

matrix([[ 7, 10],
        [15, 22]])

In [44]:
# reverse
A = np.mat([[1, 2], [3, 4]])
np.linalg.inv(A)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [49]:
# 解方程
A = np.mat([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
B = np.mat([[6], [-4], [27]])
#np.dot(np.linalg.inv(A), B) 一样的
np.linalg.solve(A, B)

matrix([[ 5.],
        [ 3.],
        [-2.]])